version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: gem install bundler --pre
      - run: bundle install
      - run: npm install
      - run: bash automated_build.sh
  test:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: echo "done"
  deploy:
    steps:
      - checkout
      - run: npm run deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - test
